### ISSUE TITLE
No longer working in node?

### ISSUE THREAD

**Issue by ofrobots** [v8/web-tooling-benchmark#50]
After a fresh clone and npm install:

```shell
~/src/web-tooling-benchmark master
❯ node dist/cli.js
/Users/ofrobots/src/web-tooling-benchmark/dist/cli.js:52067
/* WEBPACK VAR INJECTION */(function(global) {var scope = (typeof self !== "undefined" && self) || window;
                                                                                                   ^

ReferenceError: window is not defined
    at Object.<anonymous> (/Users/ofrobots/src/web-tooling-benchmark/dist/cli.js:52067:100)
    at Object.<anonymous> (/Users/ofrobots/src/web-tooling-benchmark/dist/cli.js:52129:30)
    at __webpack_require__ (/Users/ofrobots/src/web-tooling-benchmark/dist/cli.js:25:30)
    at Object.module.exports (/Users/ofrobots/src/web-tooling-benchmark/dist/cli.js:90860:69)
    at __webpack_require__ (/Users/ofrobots/src/web-tooling-benchmark/dist/cli.js:25:30)
    at Object.toString (/Users/ofrobots/src/web-tooling-benchmark/dist/cli.js:164851:20)
    at __webpack_require__ (/Users/ofrobots/src/web-tooling-benchmark/dist/cli.js:25:30)
    at Object.<anonymous> (/Users/ofrobots/src/web-tooling-benchmark/dist/cli.js:160010:74)
    at __webpack_require__ (/Users/ofrobots/src/web-tooling-benchmark/dist/cli.js:25:30)
    at Object.<anonymous> (/Users/ofrobots/src/web-tooling-benchmark/dist/cli.js:7374:19)

```

**Comment by mathiasbynens** [comment]
Which Node.js version are you using?

**Comment by mathiasbynens** [comment]
I can reproduce the issue with Node.js v9.8.0.

The offending code is in `node_modules/timers-browserify/main.js`. timers-browserify was recently changed: https://github.com/browserify/timers-browserify/issues/34 We can work around it by defining `window = global`.

(This would have been avoided with `package-lock.json`!)

**Comment by mathiasbynens** [comment]
Unfortunately, that workaround won’t fly. `window = global` breaks Coffeescript, which then uses `window.attachEvent`. 

I’ll submit a PR to `timers-browserify` to use `this` instead of `window`.

**Comment by ofrobots** [comment]
Thanks for the fast investigation on this! A `package-lock.json` in this repo would be great indeed. I'll try the work-around in the meanwhile.

**Comment by mathiasbynens** [comment]
This is now fixed upstream.
